### ISSUE TITLE
gemSpecPages - der erste Kommentar

### ISSUE THREAD

**Issue by thorschtn** [gematik/gemSpecPages#1]
Hinterlasst gerne weitere Kommentare zum neuen Prototypen für die webbasierte Veröffentlichung: https://gemspec.dev.ccs.gematik.solutions/docs/

Auf jeder Seite habt Ihr oben rechts die Möglichkeit: "dieses Dokument kommentieren".

**Comment by 20231902** [comment]
- Die Suche funktioniert (meistens) sehr gut, wenn man jedoch so viele Treffer hat, dass es mehr als eine Seite ist, dann muss man wieder an den Anfang der Seite, um eine Seite weiterblättern zu können. Schön wäre die Blätterleiste auch am Ende der Suchergebnisliste.
- Toll wäre es auch, wenn einzelne Themen geclustert wären, also alles zum eRezept, zur ePA usw. gehört, in einem Bereich

**Comment by thorschtn** [comment]
Testkommentar entfernt.

**Comment by thorschtn** [comment]
> * Die Suche funktioniert (meistens) sehr gut, wenn man jedoch so viele Treffer hat, dass es mehr als eine Seite ist, dann muss man wieder an den Anfang der Seite, um eine Seite weiterblättern zu können. Schön wäre die Blätterleiste auch am Ende der Suchergebnisliste.
> * Toll wäre es auch, wenn einzelne Themen geclustert wären, also alles zum eRezept, zur ePA usw. gehört, in einem Bereich

Danke für den Hinweis. Die Pagination am Ende der Seite haben wir zwischenzeitlich umgesetzt, der Cluster nach Anwendungen ist mittelfristig geplant.
