### ISSUE TITLE
Online-Reader: diacritic-agnostic search

### ISSUE THREAD

**Issue by vadi2** [gematik/gemSpecPages#10]
Thanks for the brilliant website - it's really handy!

It would be nice if diacritic-agnostic search was supported - so that, as an example, Prufungsnachweis turns up the same results as Prüfungsnachweis. Otherwise it makes life a bit more challenging for those without a native keyboard 🙂

**Comment by thorschtn** [comment]
Fixed:
https://gemspec.gematik.de/docs/search/index.html?advanced=false&source=spec&from=0&size=10&q=Prufungsnachweis vs. https://gemspec.gematik.de/docs/search/index.html?advanced=false&source=spec&from=0&size=10&q=Pr%C3%BCfungsnachweis
