### ISSUE TITLE
gemILF_Neues_Dokument_V0.0.1 - "Neues Dokument" Eintrag im Nav-Menü unter Implementierungsleitfäden

### ISSUE THREAD

**Issue by Kastobi** [gematik/gemSpecPages#16]
https://gemspec.gematik.de/docs/gemILF/Neues_Dokument/gemILF_Neues_Dokument_V0.0.1/

Verweist auf die Spezifikation E-Rezept-Frontend des Versicherten.

Steht auch im Nav-Menü unter den Implementierungsleitfäden als "Neues Dokument"

Danke! 😃

**Comment by thorschtn** [comment]
Fixed!
