### ISSUE TITLE
gemSpec_DS_Hersteller_V1.2.0

### ISSUE THREAD

**Issue by volkerdoerr** [gematik/gemSpecPages#3]
Und hier noch ein Testkommentar, diesmal aber ohne Link für torschtn, mal sehen, ob der auch kommentiert wird :-)

**Comment by thorschtn** [comment]
Lieber Volker, ab sofort werden die Issues hier auch nachverfolgt und behandelt. Bitte beachtet, dass die Kommentierung hier an dieser Stelle aktuell noch kein Teil der produktiven Abstimmungsprozesse ist, sondern eher Teil der frühen Eruierung möglicher Lösungen.

**Comment by thorschtn** [comment]
Lieber Volker, ab sofort werden Issues hier auch beobachtet und nachverfolgt.
Bitte beachte, dass Github Issues aktuell noch kein Teil der produktiven Abstimmungsprozesse sind, sondern eher der Eruierung künftiger Kollaborationsmöglichkeiten dienen.

**Comment by thorschtn** [comment]
Testkommentar entfernt.
