### ISSUE TITLE
Ein kleiner Typo in Kapitel 3.8

### ISSUE THREAD

**Issue by sonerd** [gematik/gemSpecPages#6]
Im Kapitel 3.8 ist ein Typo im 2. Paragraphen, welches mit "Im Behandlungskontext wird vom PS im Zusammenhang..." beginnt. Am Ende des Satzes steht "einstellt".  Sollte wahrscheinlich "eingestellt" sein.

**Comment by thorschtn** [comment]
Danke für den Hinweis, ist in der nächsten Version gefixed.
