### ISSUE TITLE
Typo in UML-Diagramm "Hanshake"

### ISSUE THREAD

**Issue by dirkexe** [gematik/gemSpecPages#7]
[A_25160](https://gemspec.gematik.de/docs/gemSpec/gemSpec_eHealth-CardLink/gemSpec_eHealth-CardLink_V1.0.0/) - eHealth-CardLink - Card Communication Interface, API-Dokumentation

Abbildung 4: Ablauf Prüfungsnachweis (PNW) erzeugen

Beobachtet: "Hanshake"
Erwartet: "Handshake"

![A_25160_Typo](https://github.com/gematik/gemSpecPages/assets/8550081/6db7c824-4992-4d47-9ce0-4ff3fe855ef6)

**Comment by thorschtn** [comment]
Danke, wir kümmern uns!

**Comment by thorschtn** [comment]
**gematik Stellungnahme: OK**

Danke, wir kümmern uns!
