### ISSUE TITLE
Suche nach Afo ID: Suchbegriff ist case sensitive

### ISSUE THREAD

**Issue by krumeich** [gematik/gemSpecPages#8]
Bei der Direktuche nach der AFO-ID ist die Suche case-sensitive:

a_15535 -> Keine Treffer
A_15525 -> Afo gefunden

Können Sie das so beheben, dass die Afo unabhängig von Groß-/Kleinschreibung gefunden wird? Danke!

**Comment by vadi2** [comment]
Related to this: https://github.com/gematik/gemSpecPages/issues/10

**Comment by thorschtn** [comment]
Fixed: AFO-Direkt-Suche auf Case Insensitive umgestellt.
